# Site settings
title: Ire Aderinokun CV
email: ire@ireaderinokun.com
description: Curriculumn Vitae for Ire Aderinokun - Professional Website Designer and Front=end Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


